/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmware.bdd.software.mgmt.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ClusterAction implements org.apache.thrift.TEnum {
  QUERY(1),
  CREATE(2),
  UPDATE(3),
  START(4),
  STOP(5),
  DESTROY(6),
  CONFIGURE(7);

  private final int value;

  private ClusterAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ClusterAction findByValue(int value) { 
    switch (value) {
      case 1:
        return QUERY;
      case 2:
        return CREATE;
      case 3:
        return UPDATE;
      case 4:
        return START;
      case 5:
        return STOP;
      case 6:
        return DESTROY;
      case 7:
        return CONFIGURE;
      default:
        return null;
    }
  }
}
