/***************************************************************************
 * Copyright (c) 2012-2013 VMware, Inc. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***************************************************************************/
/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmware.bdd.software.mgmt.thrift;



public enum ClusterAction implements org.apache.thrift.TEnum {
  QUERY(1),
  CREATE(2),
  UPDATE(3),
  START(4),
  STOP(5),
  DESTROY(6),
  CONFIGURE(7);

  private final int value;

  private ClusterAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ClusterAction findByValue(int value) { 
    switch (value) {
      case 1:
        return QUERY;
      case 2:
        return CREATE;
      case 3:
        return UPDATE;
      case 4:
        return START;
      case 5:
        return STOP;
      case 6:
        return DESTROY;
      case 7:
        return CONFIGURE;
      default:
        return null;
    }
  }
}
