/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmware.bdd.software.mgmt.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ServerStatus implements org.apache.thrift.TEnum {
  VM_READY(1),
  SERVICE_READY(2),
  BOOTSTRAP_FAILED(3);

  private final int value;

  private ServerStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServerStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return VM_READY;
      case 2:
        return SERVICE_READY;
      case 3:
        return BOOTSTRAP_FAILED;
      default:
        return null;
    }
  }
}
