#!/usr/bin/python

import crypt, string, random, sys

salt_chars = string.ascii_letters + string.digits + './'
salt = ''.join([random.choice(salt_chars) for x in range(16)])

password = sys.stdin.readline().strip('\n')

encpw = crypt.crypt(password, '$6$%s$' % salt)

sys.stdout.write(encpw + '\n')
