package com.vmware.bdd.apitypes;

public enum ClusterStatus {
   RUNNING, PROVISIONING, PROVISION_ERROR, UPGRADING, UPDATING, DELETING, STOPPED, ERROR, STOPPING, STARTING, CONFIGURING, CONFIGURE_ERROR, NA, VHM_RUNNING, VMRECONFIGURING, MAINTENANCE, UPGRADE_ERROR
}
