#!/usr/bin/python

# ***** BEGIN LICENSE BLOCK *****
#    Copyright (c) 2012 VMware, Inc. All Rights Reserved.
#    Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ***** END LICENSE BLOCK *****

# Read machine.id as a json string, and get value for key given on command line

try:
    import json
except ImportError:
    import simplejson as json
import sys, os
from get_json_value import getValue

if len(sys.argv) != 2:
   sys.stderr.write('Usage: %s <key>\n' % sys.argv[0])
   sys.exit(-1)

machineIdCmd = "/usr/sbin/vmware-rpctool machine.id.get"
machineIdProcess = os.popen(machineIdCmd, 'r')
machineId = machineIdProcess.read()
r = machineIdProcess.close()
if r:
   sys.stderr.write(machineIdCmd + ' returned ' + str(r) + '\n')
   sys.exit(-1)

value = getValue(sys.argv[0], machineId, sys.argv[1])
if value is not None:
   sys.stdout.write(value)
   sys.exit(0)
else:
   sys.exit(-1)
